- name: Create Jellyfin Directory
  ansible.builtin.file:
    path: "{{ jellyfin_docker_path }}"
    owner: "{{ jellyfin_docker_file_owner }}"
    group: "{{ jellyfin_docker_file_group }}"
    state: directory
    mode: 0755

- name: Create Jellyfin Docker Compose File
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ jellyfin_docker_path }}/docker-compose.yml"
    owner: "{{ jellyfin_docker_file_owner }}"
    group: "{{ jellyfin_docker_file_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart jellyfin

- name: Validate Docker Compose File
  ansible.builtin.command: docker compose config --quiet
  args:
    chdir: "{{ jellyfin_docker_path }}"
  changed_when: false

- name: Startup Container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ jellyfin_docker_path }}"
  register: jellyfin_container_startup
  changed_when: "'Started' in jellyfin_container_startup.stdout"
