# example nfs configuration
jellyfin_docker_volumes:
- name: movies
  mount: /movies
  driver_opts:
    type: nfs
    o: "addr=192.168.1.2,rsize=8192,wsize=8192,timeo=14,intr,rw,hard,nfsvers=4"
    device: ":/movies"
