- name: Create watchtower directory
  ansible.builtin.file:
    path: "{{ watchtower_docker_path }}"
    owner: "{{ watchtower_docker_owner }}"
    group: "{{ watchtower_docker_group }}"
    state: directory
    mode: 0755

- name: Create watchtower docker compose deployment
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ watchtower_docker_path }}/docker-compose.yml"
    owner: "{{ watchtower_docker_owner }}"
    group: "{{ watchtower_docker_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart watchtower

- name: Validate watchtower docker compose deployment
  ansible.builtin.command: docker compose config --quiet
  args:
    chdir: "{{ watchtower_docker_path }}"
  changed_when: false

- name: Startup watchtower docker compose deployment
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ watchtower_docker_path }}"
  register: watchtower_container_startup
  changed_when: "'Started' in watchtower_container_startup.stdout"
