- name: Restart jellyfin vue container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain restart
  args:
    chdir: "{{ jellyfin_vue_docker_path }}"
  changed_when: true
  listen: restart jellyfin vue
